### ISSUE TITLE
Error when trying to compile the solution

### ISSUE THREAD

**Issue by pitelm** [Microsoft/Windows-appsample-remote-system-sessions#3]
Hi,

When I clone the repo and then try and compile it, I am getting these errors:

> 1>  C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(335,13): error MSB4064: The "EnableTypeInfoReflection" parameter is not supported by the "CompileXaml" task. Verify the parameter exists on the task, and it is a settable public instance property.
> 1>  C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(308,5): error MSB4063: The "CompileXaml" task could not be initialized with its input parameters. 

In have the latest windows 10sdk 

Anything else I need to do for the UWP to compile and run? I am a bit new to this UWP development, have normally been backend and web.

Thanks a lot

**Comment by KarlErickson** [comment]
Hi @pitelm - unfortunately, we can't reproduce these errors. I've seen similar errors in the past, however, but haven't found a consistent solution after doing a web search. I believe the issue is that there's a mismatch between dependencies, possibly related to an error that occurred during installation of one or more components. Here are some things that you might try (one at a time): do a clean/rebuild, confirm you are on the latest VS and upgrade if not, confirm you have the latest OS upgrade and upgrade if not, uninstall and reinstall the latest SDK, uninstall all versions of the SDK (if you have multiple) and then reinstall the latest. Hopefully one of these will solve your problem. If not, then you might want to ask at developercommunity.visualstudio.com. Good luck!

**Comment by ghost** [comment]
I solve the problem.

Update NuGet Package
"Microsoft.NETCore.UniversalWindowsPlatform" v6.1.9(latest version)
